// Code generated by goctl. DO NOT EDIT.
// Source: fileOps.proto

package server

import (
	"context"

	"github.com/dunzane/brainbank-file/rpc/fileOps/internal/logic"
	"github.com/dunzane/brainbank-file/rpc/fileOps/internal/svc"
	"github.com/dunzane/brainbank-file/rpc/fileOps/pb"
)

type FileOpsServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedFileOpsServer
}

func NewFileOpsServer(svcCtx *svc.ServiceContext) *FileOpsServer {
	return &FileOpsServer{
		svcCtx: svcCtx,
	}
}

func (s *FileOpsServer) UploadFile(ctx context.Context, in *pb.UploadFileRequest) (*pb.UploadFileResponse, error) {
	l := logic.NewUploadFileLogic(ctx, s.svcCtx)
	return l.UploadFile(in)
}

func (s *FileOpsServer) UpdateFile(ctx context.Context, in *pb.UpdateFileRequest) (*pb.UpdateFileResponse, error) {
	l := logic.NewUpdateFileLogic(ctx, s.svcCtx)
	return l.UpdateFile(in)
}

func (s *FileOpsServer) ListFiles(ctx context.Context, in *pb.ListFilesRequest) (*pb.ListFilesResponse, error) {
	l := logic.NewListFilesLogic(ctx, s.svcCtx)
	return l.ListFiles(in)
}

func (s *FileOpsServer) DeleteFile(ctx context.Context, in *pb.DeleteFileRequest) (*pb.DeleteFileResponse, error) {
	l := logic.NewDeleteFileLogic(ctx, s.svcCtx)
	return l.DeleteFile(in)
}
