// Code generated by goctl. DO NOT EDIT.
// Source: fileInfo.proto

package server

import (
	"context"

	"github.com/dunzane/brainbank-file/rpc/fileInfo/internal/logic"
	"github.com/dunzane/brainbank-file/rpc/fileInfo/internal/svc"
	"github.com/dunzane/brainbank-file/rpc/fileInfo/pb"
)

type FileInfoServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedFileInfoServer
}

func NewFileInfoServer(svcCtx *svc.ServiceContext) *FileInfoServer {
	return &FileInfoServer{
		svcCtx: svcCtx,
	}
}

func (s *FileInfoServer) PreviewFile(ctx context.Context, in *pb.PreviewFileRequest) (*pb.PreviewFileResponse, error) {
	l := logic.NewPreviewFileLogic(ctx, s.svcCtx)
	return l.PreviewFile(in)
}

func (s *FileInfoServer) GetFileInfo(ctx context.Context, in *pb.GetFileInfoRequest) (*pb.GetFileInfoResponse, error) {
	l := logic.NewGetFileInfoLogic(ctx, s.svcCtx)
	return l.GetFileInfo(in)
}
